# argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/marwen69/agrocd'
    targetRevision: HEAD
    path: path/to/kubernetes-manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
