# tp-foyer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-foyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-foyer
  template:
    metadata:
      labels:
        app: tp-foyer
    spec:
      containers:
        - name: tp-foyer
          image: marwenhm/devops-project:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{
                "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
                "spring.datasource.username" : "root",
                "spring.datasource.password" : "root",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
                "spring.jpa.hibernate.ddl-auto" : "update"
              }'
          ports:
            - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: tp-foyer
spec:
  selector:
    app: tp-foyer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer
